import { KaihKegiatan } from './supabase';

const todayStr = new Date().toISOString().split('T')[0];

export const INITIAL_KAIH_KEGIATAN: KaihKegiatan[] = [
  {
    id: 'kaih-s-1',
    tipe: 'sekolah',
    kelas_id: 'c1-4a',
    siswa_id: null,
    kategori_id: 2,
    kategori_nama: 'Beribadah Tepat Waktu',
    judul: 'Sholat Dhuha Berjamaah di Musholla',
    deskripsi: 'Pembiasaan sholat Dhuha bersama seluruh siswa Kelas 4A dipimpin wali kelas sebelum memulai pembelajaran jam pertama.',
    jam: '07:15 WIB',
    tanggal: todayStr,
    foto_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80',
    creator_nama: 'Bu Sari, S.Pd (Wali Kelas 4A)',
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'kaih-s-2',
    tipe: 'sekolah',
    kelas_id: 'c1-4a',
    siswa_id: null,
    kategori_id: 3,
    kategori_nama: 'Berolahraga / Aktivitas Fisik',
    judul: 'Senam Kesegaran Jasmani & Peregangan Bersama',
    deskripsi: 'Aktivitas fisik gerak badan dan jalan santai 20 menit di halaman sekolah untuk menjaga kebugaran tubuh.',
    jam: '09:00 WIB',
    tanggal: todayStr,
    foto_url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&auto=format&fit=crop&q=80',
    creator_nama: 'Bu Sari, S.Pd (Wali Kelas 4A)',
    created_at: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
  },
  {
    id: 'kaih-r-1',
    tipe: 'rumah',
    kelas_id: 'c1-4a',
    siswa_id: 's-1',
    kategori_id: 1,
    kategori_nama: 'Bangun Pagi & Merapikan Tempat Tidur',
    judul: 'Bangun Subuh & Merapikan Kamar Sendiri',
    deskripsi: 'Ananda bangun pukul 04.45 WIB, merapikan selimut, bantal, dan menyiapkan tas sekolah secara mandiri.',
    jam: '05:10 WIB',
    tanggal: todayStr,
    foto_url: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?w=800&auto=format&fit=crop&q=80',
    creator_nama: 'Pak Budi Santoso (Wali Murid)',
    apresiasi_guru: true,
    catatan_guru: 'Alhamdulillah, sangat mandiri dan tertib! Pertahankan ya Ananda.',
    created_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    siswa: {
      nama_lengkap: 'Ahmad Budi Santoso',
      kelas: { nama_kelas: 'Kelas 4A' },
    },
  },
  {
    id: 'kaih-r-2',
    tipe: 'rumah',
    kelas_id: 'c1-4a',
    siswa_id: 's-1',
    kategori_id: 5,
    kategori_nama: 'Makan Makanan Bergizi Seimbang',
    judul: 'Sarapan Sehat Sayur Bayam, Telur & Buah Pisang',
    deskripsi: 'Sarapan sebelum berangkat ke sekolah dengan gizi seimbang serta minum air putih yang cukup.',
    jam: '06:20 WIB',
    tanggal: todayStr,
    foto_url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&auto=format&fit=crop&q=80',
    creator_nama: 'Pak Budi Santoso (Wali Murid)',
    apresiasi_guru: true,
    catatan_guru: 'Hebat, sarapan bergizi membuat konsentrasi belajar makin prima.',
    created_at: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    siswa: {
      nama_lengkap: 'Ahmad Budi Santoso',
      kelas: { nama_kelas: 'Kelas 4A' },
    },
  },
];
